In [1]:
import numpy as np

# Numpy

## Task 1

In [4]:
A = np.array([[1, 2, 3, 3,1], 
              [6, 8,11, 10,7]],dtype=float)


In [23]:
print(A,type(A),
      '\n',
      A.ndim,
      '\n',
      A.shape
     )

[[ 1.  2.  3.  3.  1.]
 [ 6.  8. 11. 10.  7.]] <class 'numpy.ndarray'> 
 2 
 (2, 5)


In [24]:
#A = A.transpose()
print(A,A.shape)

[[ 1.  6.]
 [ 2.  8.]
 [ 3. 11.]
 [ 3. 10.]
 [ 1.  7.]] (5, 2)


In [14]:
mean_a = A.mean(axis = 0)

In [15]:
mean_a

array([2. , 8.4])

## Task 2

In [25]:
a_centered = A-mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [26]:
a_centered.shape

(5, 2)

## Task 3

In [49]:
a_centered_sp = a_centered[:,0] @ a_centered[:,1]

In [53]:
print(a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


In [56]:
a_centered_sp/=(a_centered[:,0].size-1)

In [57]:
a_centered_sp

2.0

## Task 4

In [58]:
np.cov(m = A.transpose())

array([[1. , 2. ],
       [2. , 4.3]])

In [59]:
print('Ok, 2=2')

Ok, 2=2


# Pandas

## Task 1

In [60]:
import pandas as pd

In [71]:
authors_id = [1,2,3]
authors_name = ['Тургенев', 'Чехов', 'Островский']
book_authors_id = [1, 1, 1, 2, 2, 3, 3]
book_title = ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники']
price =[450, 300, 350, 500, 450, 370, 290]

In [73]:
authors = pd.DataFrame({'author_id':authors_id,
                        'author_name':authors_name})

In [68]:
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [75]:
books = pd.DataFrame({
    'author_id': book_authors_id,
    'book_title': book_title,
    'price':price
})

In [76]:
books

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

## Task 2

In [77]:
authors_price = pd.merge(authors, books, on='author_id', how='inner')

In [78]:
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

## Task 3

In [79]:
top5 = authors_price.nlargest(5, "price")
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

## Task 4

In [82]:
min_price = authors_price.groupby("author_name").agg({"price": "max"})
max_price = authors_price.groupby("author_name").agg({"price": "min"})
mean_price = authors_price.groupby("author_name").agg({"price": "mean"})

In [83]:
mean_price

price
author_name            
Островский   330.000000
Тургенев     366.666667
Чехов        475.000000

In [85]:
authors_stats = pd.concat([min_price, max_price, mean_price], axis=1)
authors_stats.columns = ['min_price','max_price','mean_price']
authors_stats

min_price  max_price  mean_price
author_name                                  
Островский         370        290  330.000000
Тургенев           450        300  366.666667
Чехов              500        450  475.000000

## Task 5

In [86]:
authors_price['cover']=['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [87]:
?pd.pivot_table

Signature:
pd.pivot_table(
    data,
    values=None,
    index=None,
    columns=None,
    aggfunc='mean',
    fill_value=None,
    margins=False,
    dropna=True,
    margins_name='All',
    observed=False,
) -> 'DataFrame'
Docstring:
Create a spreadsheet-style pivot table as a DataFrame.

The levels in the pivot table will be stored in MultiIndex objects
(hierarchical indexes) on the index and columns of the result DataFrame.

Parameters
----------
data : DataFrame
values : column to aggregate, optional
index : column, Grouper, array, or list of the previous
    If an array is passed, it must be the same length as the data. The
    list can contain any of the other types (except list).
    Keys to group by on the pivot table index.  If an array is passed,
    it is being used as the same manner as column values.
columns : column, Grouper, array, or list of the previous
    If an array is passed, it must be the same length as the data. The
    list can contain any of the other types 

In [89]:
book_info = pd.pivot_table(authors_price, values='price', index=['author_name'],
                    columns=['cover'], aggfunc=np.sum, fill_value=0)
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

In [90]:
book_info.to_pickle("book_info.pkl")

In [91]:
book_info1 = pd.read_pickle("book_info.pkl")

In [92]:
book_info == book_info1

cover        мягкая  твердая
author_name                 
Островский     True     True
Тургенев       True     True
Чехов          True     True